// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Pizzapp
{
	public partial class StoryboardView : UIViewController
	{
		public StoryboardView (IntPtr handle) : base (handle)
		{
		}
	}
}
